class AppStrings {
  AppStrings._();

  static const Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // General & Common
      'app_name': 'صيانة هوم',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'save': 'حفظ',
      'close': 'إغلاق',
      'retry': 'إعادة المحاولة',
      'error': 'خطأ',
      'success': 'نجاح',
      'loading': 'جاري التحميل...',
      'currency': 'ل.س',
      'km': 'كم',
      'meter': 'م',
      'phone_number': 'رقم الهاتف',
      'name': 'الاسم',
      'date': 'التاريخ',
      'time': 'الوقت',
      'notes': 'الملاحظات',
      'details': 'التفاصيل',
      'urgent': 'عاجل ⚡',
      'scheduled': 'مجدول 📅',
      'warranty': 'ضمان 🛡️',
      'normal': 'عادي',
      'required_field': 'هذا الحقل مطلوب',

      // Navigation Tabs
      'tab_home': 'الرئيسية',
      'tab_orders': 'طلباتي',
      'tab_wallet': 'المحفظة',
      'tab_profile': 'الحساب',

      // Auth Feature
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'أدخل رقم هاتفك لتسجيل الدخول ومتابعة مهامك',
      'send_otp': 'إرسال رمز التحقق',
      'otp_verification': 'تأكيد رمز التحقق',
      'otp_sent_to': 'تم إرسال رمز التحقق المكون من 6 أرقام إلى',
      'verify_and_login': 'تحقق وتسجيل الدخول',
      'resend_otp': 'إعادة إرسال الرمز',
      'activation_title': 'تفعيل الحساب',
      'activation_subtitle': 'حسابك الفني غير مفعل حالياً. يرجى إدخال كود التفعيل من المكتب أو التواصل مع الإدارة',
      'activation_code': 'كود التفعيل',
      'activate_account': 'تفعيل الحساب',
      'select_office': 'اختيار المكتب / الفرع',
      'select_office_desc': 'يرجى اختيار المكتب التابع له لربط حسابك',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تأكيد تسجيل الخروج',
      'logout_confirm_desc': 'هل أنت متأكد من رغبتك في تسجيل الخروج من التطبيق؟',

      // Home & Dispatch
      'status_online': 'متصل',
      'status_offline': 'غير متصل',
      'online_toast': 'أنت الآن متصل وجاهز لاستلام الطلبات 🟢',
      'offline_toast': 'تم تغيير الحالة إلى غير متصل ⚪',
      'offline_blocked_toast': 'لا يمكنك تغيير حالتك إلى غير متاح أثناء وجود طلب صيانة نشط ⚠️',
      'new_order_offer': 'طلب صيانة جديد!',
      'accept_order': 'قبول الطلب',
      'decline_order': 'رفض الطلب',
      'client': 'العميل',
      'address': 'العنوان',
      'distance': 'المسافة',
      'inspection_fee': 'أجور الكشف',
      'problem_desc': 'تفاصيل المشكلة',
      'order_no': 'طلب #',

      // Order Lifecycle
      'order_accepted_header': 'طلب مقبول / قيد التوجه للعميل',
      'arrive_at_location': 'تم الوصول إلى الموقع 📍',
      'arrive_success': 'تم تسجيل وصولك إلى موقع العميل بنجاح 📍',
      'withdraw_order': 'انسحاب',
      'withdraw_confirm_title': 'الانسحاب من الطلب',
      'withdraw_confirm_desc': 'هل أنت متأكد من رغبتك في الانسحاب من هذا الطلب؟',
      'withdraw_success': 'تم الانسحاب من الطلب بنجاح',
      'arrived_header': 'تم الوصول إلى الموقع 📍',
      'send_quote_btn': 'إرسال عرض السعر للعميل 📋',
      'quote_pending_header': 'بانتظار موافقة العميل على العرض ⏳',
      'quote_pending_desc': 'تم إرسال العرض بنجاح وبانتظار موافقة العميل لبدء الصيانة ⏳',
      'quote_rejected_header': 'رفض العميل عرض السعر ⚠️',
      'quote_rejected_desc': 'قام العميل برفض عرض السعر. تم احتساب وإضافة أجور الكشفية إلى محفظتك 💼✅',
      'in_progress_header': 'قيد تنفيذ الصيانة 🛠️',
      'finish_and_closure': 'إنهاء العمل وطلب كود الإغلاق 🏁',
      'send_addon_quote': 'عرض إضافي ➕',
      'waiting_for_parts_btn': 'انتظار قطعة ⏳',
      'parts_waiting_header': 'بانتظار قطعة غيار (مهلة 72 ساعة) ⏳',
      'parts_waiting_desc': 'يمكنك استقبال طلبات أخرى أثناء انتظار القطعة',
      'resume_order_btn': 'استئناف العمل على الطلب الآن ▶️',
      'closure_pending_header': 'بانتظار كود الإغلاق من العميل 🔐',
      'enter_closure_code_btn': 'إدخال كود الإغلاق والإنهاء 🏁',
      'dispute_header': 'طلب اعتراض من العميل قيد المراجعة 🛡️',
      'dispute_reassurance': 'قدم العميل طلب اعتراض عليك وهو الآن قيد المراجعة والتدقيق من قبل فريق الإدارة.\n\nكن على ثقة تامة أننا سنضمن حقك العادل؛ وفي حال كان الحق معك سيتم اعتماد الطلب تلقائياً وفك التجميد عن كامل مستحقاتك في المحفظة 🤝✨',
      'chat_with_client': 'محادثة العميل 💬',
      'completed_header': 'مكتمل ✅',

      // Send Quote Sheet
      'send_quote_title': 'تقديم عرض سعر الصيانة',
      'send_addon_title': 'تقديم عرض إضافي (عطل غير متوقع)',
      'labor_cost': 'أجور اليد / العمل (ل.س)',
      'warranty_period': 'مدة الضمان',
      'warranty_days_15': '15 يوماً',
      'warranty_days_30': '30 يوماً',
      'warranty_days_60': '60 يوماً',
      'warranty_days_90': '90 يوماً',
      'spare_parts': 'قطع الغيار المستبدلة',
      'add_part': 'إضافة قطعة غيار',
      'part_name': 'اسم القطعة',
      'part_price': 'سعر القطعة (ل.س)',
      'part_classification': 'تصنيف القطعة',
      'class_original': 'أصلي',
      'class_commercial': 'تجاري',
      'class_standard': 'عادي',
      'capture_part_photo': 'تصوير القطعة',
      'total_quote_price': 'إجمالي العرض (شامل القطع وأجور العمل):',
      'send_quote_action': 'إرسال العرض للعميل',

      // Waiting for Parts Dialog
      'parts_dialog_title': 'طلب انتظار قطعة غيار',
      'parts_dialog_desc': 'عند تأكيد الانتظار، سيتم منحك مهلة 72 ساعة لتأمين القطعة المطلوبة.\nيمكنك خلال هذه الفترة استقبال وتنفيذ طلبات صيانة أخرى 🕒',
      'parts_note_hint': 'ملاحظة أو اسم القطعة (اختياري)',
      'confirm_waiting': 'تأكيد مهلة الانتظار',

      // Closure Request Sheet
      'closure_sheet_title': 'طلب إنهاء العمل وإصدار الكود',
      'closure_sheet_desc': 'التقط من 1 إلى 3 صور لإثبات إتمام الصيانة بنجاح ليتم إرسال كود الإغلاق الرقمي للعميل 📸',
      'add_closure_photo': 'إضافة صورة',
      'submit_closure_request': 'إرسال طلب الكود',

      // Closure Verification Dialog
      'verify_closure_title': 'تأكيد إتمام العمل وإغلاق الطلب',
      'verify_closure_desc': 'اطلب كود الإغلاق الرقمي من العميل وأدخله هنا لإغلاق الطلب وإيداع مستحقاتك في محفظتك 💼',
      'closure_code_hint': 'رمز الإغلاق',
      'verify_and_complete': 'تحقق وإنهاء 🏁',
      'order_completed_success': 'مبروك! تم إكمال الطلب بنجاح وإيداع المستحقات في محفظتك 💼🎉',

      // Wallet Feature
      'wallet_title': 'المحفظة المالية',
      'total_balance': 'الرصيد الإجمالي',
      'available_balance': 'الرصيد المتاح للسحب',
      'frozen_balance': 'الرصيد المعلق (قيد الضمان)',
      'sham_cash_card_title': 'حساب شام كاش (Sham Cash)',
      'sham_cash_linked': 'حساب مرتبط',
      'sham_cash_not_linked': 'غير مرتبط',
      'sham_cash_desc_not_linked': 'قم بربط حساب شام كاش لتتمكن من سحب أرباحك ومستحقاتك فوراً',
      'link_sham_cash_btn': 'ربط الحساب الآن',
      'edit_sham_cash_btn': 'تعديل الحساب',
      'account_holder_name': 'اسم صاحب الحساب',
      'sham_cash_number': 'رقم / معرف حساب شام كاش',
      'withdrawals_history': 'سجل عمليات السحب',
      'request_withdrawal_btn': 'طلب سحب رصيد 💸',
      'withdrawal_amount': 'مبلغ السحب (ل.س)',
      'withdrawal_fee': 'أجور التحويل',
      'net_received': 'صافي المبلغ المستلم',
      'withdrawal_status_pending': 'قيد المعالجة ⏳',
      'withdrawal_status_completed': 'تم التحويل بنجاح ✅',
      'withdrawal_status_rejected': 'مرفوض ❌',
      'view_receipt': 'عرض إشعار التحويل 🧾',
      'empty_withdrawals': 'لا توجد طلبات سحب سابقة',

      // Profile & Settings
      'profile_title': 'الحساب والملف الشخصي',
      'technician_info': 'بيانات الفني',
      'category': 'التخصص',
      'office': 'المكتب التابع له',
      'city': 'المدينة',
      'edit_profile': 'تعديل البيانات',
      'settings_section': 'الإعدادات والتفضيلات',
      'language': 'اللغة (Language)',
      'language_arabic': 'العربية (Arabic)',
      'language_english': 'الإنجليزية (English)',
      'theme_mode': 'المظهر (Theme)',
      'theme_light': 'الوضع الفاتح ☀️',
      'theme_dark': 'الوضع الداكن 🌙',
      'theme_system': 'تلقائي (حسب النظام) ⚙️',
      'notifications_setting': 'إشعارات الطلبات',
      'app_version': 'إصدار التطبيق',

      // Chat
      'chat_title': 'المحادثة الفورية',
      'type_message_hint': 'اكتب رسالتك هنا...',
      'send': 'إرسال',

      // Notifications
      'notifications_title': 'الإشعارات والتنبيهات',
      'no_notifications': 'لا توجد إشعارات جديدة',
      'mark_all_read': 'تحديد الكل كمقروء',
    },
    'en': {
      // General & Common
      'app_name': 'Home Maintenance',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'save': 'Save',
      'close': 'Close',
      'retry': 'Retry',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'currency': 'SYP',
      'km': 'km',
      'meter': 'm',
      'phone_number': 'Phone Number',
      'name': 'Name',
      'date': 'Date',
      'time': 'Time',
      'notes': 'Notes',
      'details': 'Details',
      'urgent': 'Urgent ⚡',
      'scheduled': 'Scheduled 📅',
      'warranty': 'Warranty 🛡️',
      'normal': 'Standard',
      'required_field': 'This field is required',

      // Navigation Tabs
      'tab_home': 'Home',
      'tab_orders': 'Orders',
      'tab_wallet': 'Wallet',
      'tab_profile': 'Account',

      // Auth Feature
      'login_title': 'Technician Login',
      'login_subtitle': 'Enter your mobile number to log in and receive orders',
      'send_otp': 'Send Verification Code',
      'otp_verification': 'OTP Verification',
      'otp_sent_to': 'A 6-digit verification code was sent to',
      'verify_and_login': 'Verify & Login',
      'resend_otp': 'Resend Code',
      'activation_title': 'Account Activation',
      'activation_subtitle': 'Your technician account is not active. Enter your activation code or contact management',
      'activation_code': 'Activation Code',
      'activate_account': 'Activate Account',
      'select_office': 'Select Office / Branch',
      'select_office_desc': 'Please select your assigned office to link your profile',
      'logout': 'Logout',
      'logout_confirm_title': 'Confirm Logout',
      'logout_confirm_desc': 'Are you sure you want to log out from the application?',

      // Home & Dispatch
      'status_online': 'Online',
      'status_offline': 'Offline',
      'online_toast': 'You are now online and ready to receive orders 🟢',
      'offline_toast': 'Status changed to offline ⚪',
      'offline_blocked_toast': 'You cannot go offline while an order is active in progress ⚠️',
      'new_order_offer': 'New Service Request!',
      'accept_order': 'Accept Order',
      'decline_order': 'Decline Order',
      'client': 'Client',
      'address': 'Address',
      'distance': 'Distance',
      'inspection_fee': 'Inspection Fee',
      'problem_desc': 'Problem Description',
      'order_no': 'Order #',

      // Order Lifecycle
      'order_accepted_header': 'Order Accepted / Heading to Client',
      'arrive_at_location': 'Arrived at Location 📍',
      'arrive_success': 'Your arrival has been recorded successfully 📍',
      'withdraw_order': 'Withdraw',
      'withdraw_confirm_title': 'Withdraw from Order',
      'withdraw_confirm_desc': 'Are you sure you want to withdraw from this order?',
      'withdraw_success': 'Successfully withdrew from order',
      'arrived_header': 'Arrived at Location 📍',
      'send_quote_btn': 'Send Price Quote 📋',
      'quote_pending_header': 'Waiting for Client Approval ⏳',
      'quote_pending_desc': 'Price quote sent successfully. Waiting for client approval ⏳',
      'quote_rejected_header': 'Client Rejected Quote ⚠️',
      'quote_rejected_desc': 'Client rejected the quote. Inspection fee has been credited to your wallet 💼✅',
      'in_progress_header': 'Repair in Progress 🛠️',
      'finish_and_closure': 'Complete Work & Request Code 🏁',
      'send_addon_quote': 'Add-on Quote ➕',
      'waiting_for_parts_btn': 'Wait for Parts ⏳',
      'parts_waiting_header': 'Waiting for Parts (72h Window) ⏳',
      'parts_waiting_desc': 'You can accept other orders while waiting for spare parts',
      'resume_order_btn': 'Resume Work Now ▶️',
      'closure_pending_header': 'Waiting for Client Closure Code 🔐',
      'enter_closure_code_btn': 'Enter Closure Code 🏁',
      'dispute_header': 'Client Dispute Under Review 🛡️',
      'dispute_reassurance': 'The client has filed a dispute which is now being audited by management.\n\nRest assured your rights are guaranteed; if justified, the order will complete and funds will release to your wallet 🤝✨',
      'chat_with_client': 'Chat with Client 💬',
      'completed_header': 'Completed ✅',

      // Send Quote Sheet
      'send_quote_title': 'Submit Price Quote',
      'send_addon_title': 'Submit Add-on Quote (Unexpected Flaw)',
      'labor_cost': 'Labor Cost (SYP)',
      'warranty_period': 'Warranty Period',
      'warranty_days_15': '15 Days',
      'warranty_days_30': '30 Days',
      'warranty_days_60': '60 Days',
      'warranty_days_90': '90 Days',
      'spare_parts': 'Replacement Parts',
      'add_part': 'Add Spare Part',
      'part_name': 'Part Name',
      'part_price': 'Part Price (SYP)',
      'part_classification': 'Part Grade',
      'class_original': 'Original',
      'class_commercial': 'Commercial',
      'class_standard': 'Standard',
      'capture_part_photo': 'Photo of Part',
      'total_quote_price': 'Total Quote (Labor + Parts):',
      'send_quote_action': 'Send Quote to Client',

      // Waiting for Parts Dialog
      'parts_dialog_title': 'Request Waiting for Parts',
      'parts_dialog_desc': 'Upon confirmation, you will receive a 72-hour window to acquire parts.\nYou can accept and complete other orders during this period 🕒',
      'parts_note_hint': 'Note or part name (optional)',
      'confirm_waiting': 'Confirm Waiting Window',

      // Closure Request Sheet
      'closure_sheet_title': 'Complete Job & Issue Code',
      'closure_sheet_desc': 'Capture 1 to 3 photos of the completed repair to generate the closure code for the client 📸',
      'add_closure_photo': 'Add Photo',
      'submit_closure_request': 'Submit Code Request',

      // Closure Verification Dialog
      'verify_closure_title': 'Verify & Complete Order',
      'verify_closure_desc': 'Ask the client for the digital closure code and enter it below to complete order and receive funds 💼',
      'closure_code_hint': 'Closure Code',
      'verify_and_complete': 'Verify & Complete 🏁',
      'order_completed_success': 'Congratulations! Job completed and earnings deposited into your wallet 💼🎉',

      // Wallet Feature
      'wallet_title': 'My Wallet',
      'total_balance': 'Total Balance',
      'available_balance': 'Available Balance',
      'frozen_balance': 'Held Balance (Warranty)',
      'sham_cash_card_title': 'Sham Cash Account',
      'sham_cash_linked': 'Linked',
      'sham_cash_not_linked': 'Not Linked',
      'sham_cash_desc_not_linked': 'Link your Sham Cash account to withdraw your earnings instantly',
      'link_sham_cash_btn': 'Link Account Now',
      'edit_sham_cash_btn': 'Edit Account',
      'account_holder_name': 'Account Holder Name',
      'sham_cash_number': 'Sham Cash ID / Phone',
      'withdrawals_history': 'Withdrawals History',
      'request_withdrawal_btn': 'Request Withdrawal 💸',
      'withdrawal_amount': 'Withdrawal Amount (SYP)',
      'withdrawal_fee': 'Transfer Fee',
      'net_received': 'Net Amount',
      'withdrawal_status_pending': 'Processing ⏳',
      'withdrawal_status_completed': 'Completed ✅',
      'withdrawal_status_rejected': 'Rejected ❌',
      'view_receipt': 'View Transfer Receipt 🧾',
      'empty_withdrawals': 'No withdrawal records found',

      // Profile & Settings
      'profile_title': 'Account & Profile',
      'technician_info': 'Technician Info',
      'category': 'Specialty',
      'office': 'Assigned Office',
      'city': 'City',
      'edit_profile': 'Edit Profile',
      'settings_section': 'Settings & Preferences',
      'language': 'Language',
      'language_arabic': 'العربية (Arabic)',
      'language_english': 'English',
      'theme_mode': 'Theme Mode',
      'theme_light': 'Light Mode ☀️',
      'theme_dark': 'Dark Mode 🌙',
      'theme_system': 'System Default ⚙️',
      'notifications_setting': 'Order Notifications',
      'app_version': 'App Version',

      // Chat
      'chat_title': 'Instant Chat',
      'type_message_hint': 'Type your message here...',
      'send': 'Send',

      // Notifications
      'notifications_title': 'Notifications & Alerts',
      'no_notifications': 'No new notifications',
      'mark_all_read': 'Mark all as read',
    },
  };

  static String get(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ??
        _localizedValues['ar']?[key] ??
        key;
  }
}
